server:
  port: 8072


spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
    circuitbreaker:
      resilience4j:
        enabled: true
  application:
    name: apigateway
  config:
    import: "configserver:http://127.0.0.1:8071"


logging:
  level:
    com:
      dreamquest:
        apigateway:
          filters: debug
    io:
      github:
        resilience4j: DEBUG

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      permittedNumberOfCallsInHalfOpenState: 2



