

build:
  version: "1.0"


accounts:
  message: "Welcome to DreamBank accounts related PROD APIs"
  contactDetails:
    name: "Swapnadeep Mondal - Production"
    email: "swapnadeep@dreambank.com"
  onCallSupport:
    - "(+91) 1111111111"
    - "(+91) 1111111111"