
build:
  version: "1.0"


cards:
  message: "Welcome to DreamBank cards related local APIs"
  contactDetails:
    name: "Swapnadeep Mondal - Quality Assurance"
    email: "swapnadeep@dreambank.com"
  onCallSupport:
    - "(+91) 2222222222"
    - "(+91) 2222222222"