server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:mem:microservice_loans
    driver-class-name: org.h2.Driver
    username: admin
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console


build:
  version: "1.0"


loans:
  message: "Welcome to DreamBank loans related local APIs"
  contactDetails:
    name: "Swapnadeep Mondal - Production"
    email: "swapnadeep@dreambank.com"
  onCallSupport:
    - "(+91) 1111111111"
    - "(+91) 1111111111"