server:
  port: 9000

build:
  version: "1.0"

spring:
  application:
    name: cards

  datasource:
    url: jdbc:h2:mem:microservice_cards
    driver-class-name: org.h2.Driver
    username: admin
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  profiles:
    active: prod
  config:
    import: "optional:configserver:http://127.0.0.1:8071"
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
