server:
  port: 8072


spring:
  application:
    name: apigateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000  # Connection timeout in milliseconds
        response-timeout: 8s   # Response timeout in seconds
      circuitbreaker:
        resilience4j:
          enabled: true          # Enable Resilience4j circuit breaker
  config:
    import: "configserver:http://127.0.0.1:8071"


logging:
  level:
    com:
      dreamquest:
        apigateway:
          filters: debug
    level:
      io.github.resilience4j: DEBUG
      org.springframework.cloud.gateway: DEBUG

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 2
        slowCallDurationThreshold: 8s

resilience4j.timelimiter:
  configs:
    default:
      cancelRunningFuture: false
      timeoutDuration: 15s


