#spring:
#  application:
#    name: config-server
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          searchLocations: "classpath:/config"

spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Dreamland-afk/microservice-configserver.git"
          timeout: 5
          search-paths:
            - config
          force-pull: true
          defaultLabel: main
          cloneOnStart: true
encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"



server:
  port: 8071

